include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error

    avoid_print: ignore 
    prefer_const_constructors: ignore

  exclude:
    ## let's exclude specific files specified or with regex
    - "**.*.g.dart"
    - "**.*.freezed.dart"
    - "lib/screens/home"
